version: '3'
services:
  client:
    build:
      context: ./docker/client
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app/client
    tty: true
    # command: sh -c "cd client && npm run build && npm run serve"

  server:
    build:
      context: ./docker/server
    ports:
      - 8082:8082
    volumes:
      - .:/app
    working_dir: /app/server
    tty: true

  db:
    image: mysql:5.7
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./sqls/init:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306 # change default port number
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: docker_db
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_user_pwd

  nginx:
    image: nginx
    depends_on:
      - server
    container_name: myapp-nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  mysql_data:
