version: '3'
services:
  client:
    build:
      context: ./docker/client
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    command: sh -c "cd client && npm run build && npm run serve"