version: '3'
services:
  client:
    build:
      context: ./docker/client
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app/client
    tty: true
    # command: sh -c "cd client && npm run build && npm run serve"

  server:
    build:
      context: ./docker/server
    ports:
      - 8082:8082
    volumes:
      - .:/app
    working_dir: /app/server
    tty: true